// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace ClassifyDataML.Model
{
    public class ModelOutput
        {
            [ColumnName(@"species")]
            public uint Species { get; set; }

            [ColumnName(@"sepallength")]
            public float Sepallength { get; set; }

            [ColumnName(@"sepalwidth")]
            public float Sepalwidth { get; set; }

            [ColumnName(@"petallength")]
            public float Petallength { get; set; }

            [ColumnName(@"petalwidth")]
            public float Petalwidth { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }
}
