// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ClassifyDataML.Model
{
    public class ModelInput
    {
        [ColumnName(@"species"), LoadColumn(0)]
        public float Species { get; set; }

        [ColumnName(@"sepallength"), LoadColumn(1)]
        public float Sepallength { get; set; }

        
        [ColumnName(@"sepalwidth"), LoadColumn(2)]
        public float Sepalwidth { get; set; }

        
        [ColumnName(@"petallength"), LoadColumn(3)]
        public float Petallength { get; set; }

        
        [ColumnName(@"petalwidth"), LoadColumn(4)]
        public float Petalwidth { get; set; }

    }
}
